"""Add new column to Video table

Revision ID: 99c964bbbb54
Revises: 4732d5df47e7
Create Date: 2024-10-19 17:55:49.389054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c964bbbb54'
down_revision = '4732d5df47e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_carga', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Enum('UPLOADED', 'PROCESSED', name='state'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('fecha_carga')

    # ### end Alembic commands ###
