image: python:3.11

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - test
  - build
  - publish

test:
  stage: test
  script:
    - cd flaskr
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - cd ..
    - python -m unittest discover

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - cd flaskr
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - cd flaskr
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $TAG_COMMIT
    - docker container rm -f flaskr || true
    - docker run -d -p 5000:5000 --name flaskr $TAG_COMMIT
  environment:
    name: production
    url: http://localhost:5000/
  only:
    - main

